version: "3.9"

services:

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend-ai-ui
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-ai-ui:/app
    depends_on:
      - backend